"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, CarFront, CircleDot, FileVideo, UsersRound } from "lucide-react";
import { getMediaContentSummary } from "@/data/media-sandbox";
import { FOCUS_LABELS } from "@/config/report-rules";

type Signals = { customerSignals: Array<{ name: string; value: number }>; vehicleSignals: Array<{ name: string; value: number }>; facts: { customers: number; abnormalities: number; cases: number; converted: number } };
const empty: Signals = { customerSignals: [], vehicleSignals: [], facts: { customers: 0, abnormalities: 0, cases: 0, converted: 0 } };
const SIGNAL_LABELS: Record<string, string> = { STRUCTURE: "车身结构", POWERTRAIN: "动力系统", CHASSIS: "底盘", ELECTRICAL: "电气系统", MECHANICAL: "机械部件", EXTERIOR: "外观", CABIN: "座舱", DOCUMENT: "手续" };

export default function MediaAnalysisPage() {
  const [data, setData] = useState(empty);
  useEffect(() => { fetch("/api/media-intelligence").then((response) => response.json()).then(setData).catch(() => setData(empty)); }, []);
  const content = getMediaContentSummary();
  const platforms = content.platforms;
  const maxExposure = Math.max(...platforms.map((item) => item.views), 1);
  const displayCount = (value: number) => value >= 10000 ? `${(value / 10000).toFixed(2)} 万` : value.toLocaleString("zh-CN");
  const funnel = [{ label: "内容曝光", value: content.views, display: displayCount(content.views) }, { label: "完整播放", value: content.completedViews, display: displayCount(content.completedViews) }, { label: "咨询互动", value: content.consultations, display: String(content.consultations) }, { label: "有效线索", value: content.leads, display: String(content.leads) }, { label: "成交客户", value: data.facts.converted, display: String(data.facts.converted) }];
  return <main className="workspace-page bg-dashboard-surface"><div className="mx-auto w-full max-w-[1720px] 2xl:max-w-[1880px]">
    <Link href="/media-intelligence" className="inline-flex items-center gap-1 text-sm text-dashboard-muted hover:text-dashboard-red"><ArrowLeft className="size-4" />返回运营总览</Link><div className="mt-4"><h2 className="text-2xl font-semibold tracking-[-.04em]">数据分析</h2><p className="mt-1 text-sm text-dashboard-muted">分析内容表现如何带来咨询、客户需求和成交。</p></div>
    <section className="mt-5 grid gap-4 xl:grid-cols-[1.12fr_.88fr]">
      <div className="rounded-[20px] border border-dashboard-line bg-white p-5 shadow-[0_8px_24px_rgba(28,35,40,.05)]"><div className="flex items-center justify-between"><div><h3 className="font-semibold">平台表现对比</h3><p className="mt-1 text-xs text-dashboard-muted">曝光规模与有效线索综合观察</p></div><span className="text-xs text-dashboard-muted">单位：千次</span></div><div className="mt-6 space-y-5">{platforms.map((item) => <div key={item.platform} className="grid grid-cols-[64px_minmax(0,1fr)_54px_50px] items-center gap-3"><strong className="text-sm">{item.platform}</strong><div className="relative h-8 overflow-hidden rounded-lg bg-dashboard-surface"><div className="absolute inset-y-0 left-0 rounded-lg bg-dashboard-red/15" style={{ width: `${(item.views / maxExposure) * 100}%` }} /><div className="absolute bottom-0 left-0 h-1 rounded-full bg-dashboard-red" style={{ width: `${item.completion}%` }} /></div><span className="text-right text-xs tabular-nums text-dashboard-muted">{(item.views / 1000).toFixed(1)}k</span><strong className="text-right text-sm text-dashboard-red">{item.leads}</strong></div>)}</div><div className="mt-5 flex justify-end gap-5 border-t border-dashboard-line pt-3 text-[10px] text-dashboard-muted"><span><i className="mr-1 inline-block size-2 rounded-sm bg-dashboard-red/15" />曝光量</span><span><i className="mr-1 inline-block h-1 w-4 rounded bg-dashboard-red" />完播率</span><span>右侧：有效线索</span></div></div>
      <div className="rounded-[20px] border border-dashboard-line bg-white p-5 shadow-[0_8px_24px_rgba(28,35,40,.05)]"><h3 className="font-semibold">内容转化漏斗</h3><p className="mt-1 text-xs text-dashboard-muted">从内容触达到最终成交</p><div className="mt-5 space-y-2">{funnel.map((item, index) => <div key={item.label} className="mx-auto flex h-11 items-center justify-between rounded-xl px-4 text-sm transition-all" style={{ width: `${100 - index * 9}%`, background: `rgba(179,38,48,${.06 + index * .035})` }}><span>{item.label}</span><strong className={index >= 3 ? "text-dashboard-red" : ""}>{item.display}</strong></div>)}</div></div>
    </section>
    <section className="mt-4 rounded-[20px] border border-dashboard-line bg-white p-5 shadow-[0_8px_24px_rgba(28,35,40,.05)]"><div><h3 className="font-semibold">内容与业务关联</h3><p className="mt-1 text-xs text-dashboard-muted">结合内容表现、客户关注和车辆鉴定结果，帮助选择下一条内容。</p></div><div className="mt-6 grid items-stretch gap-3 md:grid-cols-[1fr_42px_1fr_42px_1fr]"><RelationColumn icon={<FileVideo />} title="内容表现" stats={[`完播率 ${content.completion}%`, `互动率 ${content.engagement}%`, `有效线索 ${content.leads}`]} /><Connector /><RelationColumn icon={<UsersRound />} title="客户关注" stats={(data.customerSignals.length ? data.customerSignals.slice(0,3).map((item) => `${FOCUS_LABELS[item.name as keyof typeof FOCUS_LABELS] ?? item.name} ${item.value}`) : ["安全风险", "维修成本", "价格预算"])} /><Connector /><RelationColumn icon={<CarFront />} title="车辆鉴定" stats={(data.vehicleSignals.length ? data.vehicleSignals.slice(0,3).map((item) => `${SIGNAL_LABELS[item.name] ?? "其他项目"} ${item.value}`) : ["结构异常", "底盘风险", "新能源专项"])} /></div><div className="mt-5 grid grid-cols-2 gap-3 border-t border-dashboard-line pt-5 sm:grid-cols-4"><Fact label="客户需求" value={data.facts.customers} /><Fact label="车辆异常" value={data.facts.abnormalities} /><Fact label="跟进记录" value={data.facts.cases} /><Fact label="已成交" value={data.facts.converted} /></div></section>
  </div></main>;
}

function RelationColumn({ icon, title, stats }: { icon: React.ReactNode; title: string; stats: string[] }) { return <div className="rounded-2xl border border-dashboard-line bg-dashboard-surface/50 p-4"><div className="flex items-center gap-2 font-semibold text-dashboard-ink"><span className="text-dashboard-red [&_svg]:size-4">{icon}</span>{title}</div><div className="mt-3 space-y-2">{stats.map((item) => <div key={item} className="flex items-center gap-2 rounded-lg bg-white px-3 py-2 text-xs text-dashboard-muted"><CircleDot className="size-3 text-dashboard-red" />{item}</div>)}</div></div>; }
function Connector() { return <div className="hidden items-center md:flex"><div className="h-px flex-1 bg-dashboard-red/35" /><ArrowRight className="size-4 text-dashboard-red" /></div>; }
function Fact({ label, value }: { label: string; value: number }) { return <div className="text-center"><strong className="block text-2xl tracking-[-.04em]">{value}</strong><span className="text-xs text-dashboard-muted">{label}</span></div>; }
