"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowLeft, Check, ChevronRight, SlidersHorizontal, Sparkles, Target } from "lucide-react";
import { rankOpportunities } from "@/services/media-intelligence";

const goals = ["获取线索", "建立专业信任", "促进到店"];
const audiences = ["首次购车", "家庭用户", "价格敏感", "新能源关注"];

export default function MediaOpportunitiesPage() {
  const [goal, setGoal] = useState("获取线索"); const [audience, setAudience] = useState("首次购车"); const [selected, setSelected] = useState("o1");
  const items = useMemo(() => rankOpportunities({ goal, audience, platforms: ["抖音","快手","小红书","视频号"], weights: { history: 28, customer: 30, vehicle: 24, goal: 18 } }), [goal, audience]);
  const active = items.find((item) => item.id === selected) ?? items[0];
  return <main className="workspace-page bg-dashboard-surface"><div className="mx-auto w-full max-w-[1720px] 2xl:max-w-[1880px]">
    <Link href="/media-intelligence" className="inline-flex items-center gap-1 text-sm text-dashboard-muted hover:text-dashboard-red"><ArrowLeft className="size-4" />返回运营总览</Link><div className="mt-4"><h2 className="text-2xl font-semibold tracking-[-.04em]">内容机会</h2><p className="mt-1 text-sm text-dashboard-muted">结合历史表现、客户关注和车辆鉴定结果，推荐下一条内容。</p></div>
    <section className="mt-5 grid items-start gap-4 xl:grid-cols-[260px_minmax(0,1fr)_360px]">
      <aside className="rounded-[18px] border border-dashboard-line bg-white p-5 shadow-[0_7px_20px_rgba(28,35,40,.04)]"><div className="flex items-center gap-2 font-semibold"><SlidersHorizontal className="size-4 text-dashboard-red" />筛选条件</div><SelectGroup label="运营目标" options={goals} value={goal} onChange={setGoal} /><SelectGroup label="目标人群" options={audiences} value={audience} onChange={setAudience} /><div className="mt-5 rounded-xl bg-dashboard-surface p-3 text-xs leading-5 text-dashboard-muted">修改条件后，推荐结果和排序会即时更新。</div></aside>
      <section className="overflow-hidden rounded-[18px] border border-dashboard-line bg-white shadow-[0_7px_20px_rgba(28,35,40,.04)]"><div className="flex items-center justify-between border-b border-dashboard-line px-5 py-4"><div><h3 className="font-semibold">推荐选题</h3><p className="mt-1 text-xs text-dashboard-muted">{goal} · {audience}</p></div><span className="text-xs text-dashboard-muted">共 {items.length} 项</span></div><div className="divide-y divide-dashboard-line">{items.map((item, index) => <button key={item.id} onClick={() => setSelected(item.id)} className={`flex w-full items-start gap-3 p-4 text-left transition-colors hover:bg-dashboard-surface ${active.id === item.id ? "bg-dashboard-red-soft/45" : ""}`}><span className={`flex size-8 shrink-0 items-center justify-center rounded-lg text-xs font-semibold ${index === 0 ? "bg-dashboard-red text-white" : "bg-dashboard-surface text-dashboard-muted"}`}>0{index + 1}</span><span className="min-w-0 flex-1"><strong className="block leading-6">{item.title}</strong><span className="mt-2 flex flex-wrap gap-1.5"><i className="rounded-md bg-dashboard-surface px-2 py-1 text-[10px] not-italic text-dashboard-muted">{item.type}</i><i className="rounded-md bg-white px-2 py-1 text-[10px] not-italic text-dashboard-red">{item.topic}</i></span></span><span className="text-right"><strong className="block text-xl text-dashboard-red">{item.score}</strong><ChevronRight className="ml-auto mt-2 size-4 text-dashboard-muted" /></span></button>)}</div></section>
      <aside className="rounded-[18px] border border-dashboard-line bg-white p-5 shadow-[0_7px_20px_rgba(28,35,40,.04)] xl:sticky xl:top-24"><div className="flex items-center justify-between"><span className="text-[10px] font-semibold tracking-[.12em] text-dashboard-red">选题详情</span><strong className="text-2xl text-dashboard-red">{active.score}</strong></div><h3 className="mt-4 text-xl font-semibold leading-8">{active.title}</h3><div className="mt-5 space-y-2">{active.reasons.map((reason) => <div key={reason} className="flex items-center gap-2 rounded-xl bg-dashboard-surface px-3 py-2.5 text-xs"><Check className="size-3.5 text-dashboard-red" />{reason}</div>)}</div><div className="mt-5 border-t border-dashboard-line pt-4"><div className="flex items-center gap-2 text-sm font-semibold"><Target className="size-4 text-dashboard-red" />内容方向</div><p className="mt-2 text-sm leading-6 text-dashboard-muted">从消费者真实疑问切入，用车辆鉴定事实说明风险边界，再引导用户领取完整检查清单。</p></div><button className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-dashboard-red px-4 py-3 text-sm font-medium text-white"><Sparkles className="size-4" />生成内容建议</button></aside>
    </section>
  </div></main>;
}

function SelectGroup({ label, options, value, onChange }: { label: string; options: string[]; value: string; onChange: (value: string) => void }) { return <div className="mt-5"><div className="mb-2 text-xs text-dashboard-muted">{label}</div><div className="space-y-1.5">{options.map((option) => <button key={option} onClick={() => onChange(option)} className={`flex w-full items-center justify-between rounded-xl px-3 py-2.5 text-left text-xs ${value === option ? "bg-dashboard-red-soft font-medium text-dashboard-red" : "bg-dashboard-surface text-dashboard-muted hover:text-dashboard-ink"}`}>{option}{value === option && <Check className="size-3.5" />}</button>)}</div></div>; }
